
import { translateUiText } from '../i18n/uiTranslation';// Topic-Based Categories Configuration
// Each topic contains mixed question types (Never Have I Ever, Would You Rather, etc.)

export const TOPIC_CATEGORIES = {
    relationship: {
        id: 'relationship',
        title: "Relationship",
        subtitle: "Bond, trust\nand closeness",
        emoji: '💞',
        color: '#E11D48',
        
        gradient: ['#FFE0EA', '#FFC4D6'],
        bgGradient: ['#FFF1F5', '#FFE4EC'],
        textColor: '#A8174A',
        description: "Questions about your relationship dynamics",
        questionCount: 0,
    },
    sexlove: {
        id: 'sexlove',
        title: "Sex & Love",
        subtitle: "Desire, romance\nand intimacy",
        emoji: '❤️',
        color: '#DB2777',
        gradient: ['#FFC1DA', '#F9A8D4'],
        bgGradient: ['#FDF2F8', '#FCE7F3'],
        textColor: '#9D174D',
        description: "Questions about romance and physical intimacy",
        isAdult: true,
        questionCount: 0,
    },
    coupletherapy: {
        id: 'coupletherapy',
        title: "Couple Therapy",
        subtitle: "Repair, listen\nand grow",
        emoji: '🫶',
        color: '#0D9488',
        image:require('../../assets/home/couple-therapy.png'),
        gradient: ['#A7F3D0', '#CCFBF1'],
        bgGradient: ['#ECFDF5', '#CCFBF1'],
        textColor: '#0F766E',
        description: "Questions for reflection and healthy repair",
        questionCount: 0,
    },
    longdistance: {
        id: 'longdistance',
        title: "Long Distance",
        subtitle: "Miss, plan\nand reconnect",
        emoji: '🌙',
        color: '#2563EB',
        image:require('../../assets/home/long-distance.png'),
        gradient: ['#BFDBFE', '#C7D2FE'],
        bgGradient: ['#EFF6FF', '#E0E7FF'],
        textColor: '#1D4ED8',
        description: "Questions for couples apart or traveling",
        questionCount: 0,
    },
    naughty: {
        id: 'naughty',
        title: "Naughty",
        subtitle: "Flirty, spicy\nand playful",
        emoji: '🔥',
        color: '#F43F5E',
        image:require("../../assets/home/naughty.png"),
        gradient: ['#FDA4AF', '#FDBA74'],
        bgGradient: ['#FFF1F2', '#FFEDD5'],
        textColor: '#BE123C',
        description: "Playful and spicy questions",
        isAdult: true,
        questionCount: 0,
    },
    gossip: {
        id: 'gossip',
        title: "Gossip",
        subtitle: "Tea, takes\nand secrets",
        emoji: '☕',
        image:require("../../assets/home/gossip.png"),
        color: '#9333EA',
        gradient: ['#E9D5FF', '#F5D0FE'],
        bgGradient: ['#FAF5FF', '#FCE7F3'],
        textColor: '#7E22CE',
        description: "Fun questions about drama, opinions, and stories",
        questionCount: 0,
    },
    money: {
        id: 'money',
        title: "Money",
        subtitle: "Build security\ntogether",
        emoji: '💰',
        color: '#10B981',
        image: require('../../assets/home/money-bag.png'),
        gradient: ['#B6EBCF', '#D7F4DE'],
        bgGradient: ['#E6FFFA', '#D1FAE5'],
        textColor: '#087D61',
        description: "Financial questions and preferences",
        questionCount: 0,
    },
    gettoknow: {
        id: 'gettoknow',
        title: "Get To Know",
        subtitle: "Stories, quirks\nand memories",
        emoji: '✨',
        color: '#7C3AED',
        image:require("../../assets/home/get-to-know.png"),
        gradient: ['#DDD6FE', '#E9D5FF'],
        bgGradient: ['#F5F3FF', '#FAF5FF'],
        textColor: '#6D28D9',
        description: "Questions to discover each other more deeply",
        questionCount: 0,
    },
    travel: {
        id: 'travel',
        title: "Travel",
        subtitle: "Explore places\ntogether",
        emoji: '✈️',
        color: '#F59E0B',
        image: require('../../assets/home/travel-plane.png'),
        gradient: ['#FFC35C', '#FFD780'],
        bgGradient: ['#FEF3C7', '#FEF9C3'],
        textColor: '#A45B13',
        description: "Travel dreams and adventures",
        questionCount: 0,
    },
    family: {
        id: 'family',
        title: "Family",
        subtitle: "Kids\n& Future",
        emoji: '👨‍👩‍👧‍👦',
        color: '#EC4899',
        image: require('../../assets/home/family.png'),
        gradient: ['#FFB8D0', '#FFD6E4'],
        bgGradient: ['#FDF2F8', '#FCE7F3'],
        textColor: '#B63567',
        description: "Family and future plans",
        questionCount: 0,
    },
    future: {
        id: 'future',
        title: "Future",
        subtitle: "Dream, plan\nand imagine",
        emoji: '🔮',
        color: '#A855F7',
        image: require('../../assets/home/future-crystal.png'),
        gradient: ['#D9B6FF', '#C79BFF'],
        bgGradient: ['#F5F3FF', '#E9D5FF'],
        textColor: '#7341C8',
        description: "Questions about your future together",
        questionCount: 0,
    },
};

// Question types that can exist within any topic
export const QUESTION_TYPES = {
    likelyto: { id: 'likelyto', title: "Who is more likely...", emoji: '⚖️' },
    neverhaveiever: { id: 'neverhaveiever', title: "Never have I ever...", emoji: '🤫' },
    wouldyourather: { id: 'wouldyourather', title: "Would you rather...", emoji: '🤔' },
    knowledge: { id: 'knowledge', title: "How well do you know me...", emoji: '🧠' },
    agreement: { id: 'agreement', title: "Can we match answers...", emoji: '🎯' },
    preference: { id: 'preference', title: "This or that...", emoji: '💜' },
    scale: { id: 'scale', title: "Rate yourself...", emoji: '📊' },
    scenario: { id: 'scenario', title: "What if...", emoji: '🎭' },
    finishsentence: { id: 'finishsentence', title: "Finish the sentence...", emoji: '✏️' },
    opinion: { id: 'opinion', title: "Hot takes...", emoji: '🔥' },
};

// Keep old config for backwards compatibility (can be removed later)
export const DEFAULT_CATEGORY_CONFIG = TOPIC_CATEGORIES;
