export const emojis = [
    { id: 'angry', emoji: '😠', label: 'Angry', lottieSource: require('../../assets/emojis/angry.json') },
    { id: 'anguished', emoji: '😧', label: 'Anguished', lottieSource: require('../../assets/emojis/anguished.json') },
    { id: 'anxious-with-sweat', emoji: '😰', label: 'Anxious with Sweat', lottieSource: require('../../assets/emojis/anxious-with-sweat.json') },
    { id: 'astonished', emoji: '😲', label: 'Astonished', lottieSource: require('../../assets/emojis/astonished.json') },
    { id: 'bandage-face', emoji: '🤕', label: 'Bandage Face', lottieSource: require('../../assets/emojis/bandage-face.json') },
    { id: 'big-frown', emoji: '☹️', label: 'Big Frown', lottieSource: require('../../assets/emojis/big-frown.json') },
    { id: 'blush', emoji: '😊', label: 'Blush', lottieSource: require('../../assets/emojis/blush.json') },
    { id: 'chuckling', emoji: '🤭', label: 'Chuckling', lottieSource: require('../../assets/emojis/chuckling.json') },
    { id: 'clown', emoji: '🤡', label: 'Clown', lottieSource: require('../../assets/emojis/clown.json') },
    { id: 'cold-face', emoji: '🥶', label: 'Cold Face', lottieSource: require('../../assets/emojis/cold-face.json') },
    { id: 'concerned', emoji: '😟', label: 'Concerned', lottieSource: require('../../assets/emojis/concerned.json') },
    { id: 'cry', emoji: '😢', label: 'Cry', lottieSource: require('../../assets/emojis/cry.json') },
    { id: 'cursing', emoji: '🤬', label: 'Cursing', lottieSource: require('../../assets/emojis/cursing.json') },
    { id: 'diagonal-mouth', emoji: '🫤', label: 'Diagonal Mouth', lottieSource: require('../../assets/emojis/diagonal-mouth.json') },
    { id: 'disguise', emoji: '🥸', label: 'Disguise', lottieSource: require('../../assets/emojis/disguise.json') },
    { id: 'distraught', emoji: '😩', label: 'Distraught', lottieSource: require('../../assets/emojis/distraught.json') },
    { id: 'dizzy-face', emoji: '😵', label: 'Dizzy Face', lottieSource: require('../../assets/emojis/dizzy-face.json') },
    { id: 'drool', emoji: '🤤', label: 'Drool', lottieSource: require('../../assets/emojis/drool.json') },
    { id: 'exhale', emoji: '😮‍💨', label: 'Exhale', lottieSource: require('../../assets/emojis/exhale.json') },
    { id: 'face-in-clouds', emoji: '😶‍🌫️', label: 'Face in Clouds', lottieSource: require('../../assets/emojis/face-in-clouds.json') },
    { id: 'flushed', emoji: '😳', label: 'Flushed', lottieSource: require('../../assets/emojis/flushed.json') },
    { id: 'frown', emoji: '🙁', label: 'Frown', lottieSource: require('../../assets/emojis/frown.json') },
    { id: 'grin-sweat', emoji: '😅', label: 'Grin Sweat', lottieSource: require('../../assets/emojis/grin-sweat.json') },
    { id: 'grin', emoji: '😁', label: 'Grin', lottieSource: require('../../assets/emojis/grin.json') },
    { id: 'grinning', emoji: '😀', label: 'Grinning', lottieSource: require('../../assets/emojis/grinning.json') },
    { id: 'hand-over-mouth', emoji: '🫢', label: 'Hand Over Mouth', lottieSource: require('../../assets/emojis/hand-over-mouth.json') },
    { id: 'happy-cry', emoji: '🥹', label: 'Happy Cry', lottieSource: require('../../assets/emojis/happy-cry.json') },
    { id: 'head-nod', emoji: '🙂‍↕️', label: 'Head Nod', lottieSource: require('../../assets/emojis/head-nod.json') },
    { id: 'heart-eyes', emoji: '😍', label: 'Heart Eyes', lottieSource: require('../../assets/emojis/heart-eyes.json') },
    { id: 'heart-face', emoji: '🥰', label: 'Heart Face', lottieSource: require('../../assets/emojis/heart-face.json') },
    { id: 'holding-back-tears', emoji: '🥺', label: 'Holding Back Tears', lottieSource: require('../../assets/emojis/holding-back-tears.json') },
    { id: 'hot-face', emoji: '🥵', label: 'Hot Face', lottieSource: require('../../assets/emojis/hot-face.json') },
    { id: 'hug-face', emoji: '🤗', label: 'Hug Face', lottieSource: require('../../assets/emojis/hug-face.json') },
    { id: 'imp-frown', emoji: '👿', label: 'Imp Frown', lottieSource: require('../../assets/emojis/imp-frown.json') },
    { id: 'imp-smile', emoji: '😈', label: 'Imp Smile', lottieSource: require('../../assets/emojis/imp-smile.json') },
    { id: 'joy', emoji: '😂', label: 'Joy', lottieSource: require('../../assets/emojis/joy.json') },
    { id: 'kissing-closed-eyes', emoji: '😚', label: 'Kissing Closed Eyes', lottieSource: require('../../assets/emojis/kissing-closed-eyes.json') },
    { id: 'kissing-heart', emoji: '😘', label: 'Kissing Heart', lottieSource: require('../../assets/emojis/kissing-heart.json') },
    { id: 'kissing', emoji: '😗', label: 'Kissing', lottieSource: require('../../assets/emojis/kissing.json') },
    { id: 'laughing', emoji: '😆', label: 'Laughing', lottieSource: require('../../assets/emojis/laughing.json') },
    { id: 'loudly-crying', emoji: '😭', label: 'Loudly Crying', lottieSource: require('../../assets/emojis/loudly-crying.json') },
    { id: 'mask', emoji: '😷', label: 'Mask', lottieSource: require('../../assets/emojis/mask.json') },
    { id: 'melting', emoji: '🫠', label: 'Melting', lottieSource: require('../../assets/emojis/melting.json') },
    { id: 'mind-blown', emoji: '🤯', label: 'Mind Blown', lottieSource: require('../../assets/emojis/mind-blown.json') },
    { id: 'money-face', emoji: '🤑', label: 'Money Face', lottieSource: require('../../assets/emojis/money-face.json') },
    { id: 'monocle', emoji: '🧐', label: 'Monocle', lottieSource: require('../../assets/emojis/monocle.json') },
    { id: 'moon-face-first-quarter', emoji: '🌛', label: 'Moon Face First Quarter', lottieSource: require('../../assets/emojis/moon-face-first-quarter.json') },
    { id: 'moon-face-last-quarter', emoji: '🌜', label: 'Moon Face Last Quarter', lottieSource: require('../../assets/emojis/moon-face-last-quarter.json') },
    { id: 'mouth-open', emoji: '😮', label: 'Mouth Open', lottieSource: require('../../assets/emojis/mouth-open.json') },
    { id: 'nerd-face', emoji: '🤓', label: 'Nerd Face', lottieSource: require('../../assets/emojis/nerd-face.json') },
    { id: 'neutral-face', emoji: '😐', label: 'Neutral Face', lottieSource: require('../../assets/emojis/neutral-face.json') },
    { id: 'partying-face', emoji: '🥳', label: 'Partying Face', lottieSource: require('../../assets/emojis/partying-face.json') },
    { id: 'peeking', emoji: '🫣', label: 'Peeking', lottieSource: require('../../assets/emojis/peeking.json') },
    { id: 'pensive', emoji: '😔', label: 'Pensive', lottieSource: require('../../assets/emojis/pensive.json') },
    { id: 'pleading', emoji: '🥺', label: 'Pleading', lottieSource: require('../../assets/emojis/pleading.json') },
    { id: 'poop', emoji: '💩', label: 'Poop', lottieSource: require('../../assets/emojis/poop.json') },
    { id: 'rage', emoji: '😡', label: 'Rage', lottieSource: require('../../assets/emojis/rage.json') },
    { id: 'raised-eyebrow', emoji: '🤨', label: 'Raised Eyebrow', lottieSource: require('../../assets/emojis/raised-eyebrow.json') },
    { id: 'relieved', emoji: '😌', label: 'Relieved', lottieSource: require('../../assets/emojis/relieved.json') },
    { id: 'rofl', emoji: '🤣', label: 'ROFL', lottieSource: require('../../assets/emojis/rofl.json') },
    { id: 'rolling-eyes', emoji: '🙄', label: 'Rolling Eyes', lottieSource: require('../../assets/emojis/rolling-eyes.json') },
    { id: 'sad', emoji: '😞', label: 'Sad', lottieSource: require('../../assets/emojis/sad.json') },
    { id: 'salute', emoji: '🫡', label: 'Salute', lottieSource: require('../../assets/emojis/salute.json') },
    { id: 'scared', emoji: '😨', label: 'Scared', lottieSource: require('../../assets/emojis/scared.json') },
    { id: 'screaming', emoji: '😱', label: 'Screaming', lottieSource: require('../../assets/emojis/screaming.json') },
    { id: 'shaking-face', emoji: '🫨', label: 'Shaking Face', lottieSource: require('../../assets/emojis/shaking-face.json') },
    { id: 'shushing-face', emoji: '🤫', label: 'Shushing Face', lottieSource: require('../../assets/emojis/shushing-face.json') },
    { id: 'sick', emoji: '🤢', label: 'Sick', lottieSource: require('../../assets/emojis/sick.json') },
    { id: 'sleep', emoji: '😴', label: 'Sleep', lottieSource: require('../../assets/emojis/sleep.json') },
    { id: 'sleepy', emoji: '😪', label: 'Sleepy', lottieSource: require('../../assets/emojis/sleepy.json') },
    { id: 'slightly-frowning', emoji: '🙁', label: 'Slightly Frowning', lottieSource: require('../../assets/emojis/slightly-frowning.json') },
    { id: 'slightly-happy', emoji: '🙂', label: 'Slightly Happy', lottieSource: require('../../assets/emojis/slightly-happy.json') },
    { id: 'smile-with-big-eyes', emoji: '😃', label: 'Smile with Big Eyes', lottieSource: require('../../assets/emojis/smile-with-big-eyes.json') },
    { id: 'smile', emoji: '😄', label: 'Smile', lottieSource: require('../../assets/emojis/smile.json') },
    { id: 'smirk', emoji: '😏', label: 'Smirk', lottieSource: require('../../assets/emojis/smirk.json') },
    { id: 'sneeze', emoji: '🤧', label: 'Sneeze', lottieSource: require('../../assets/emojis/sneeze.json') },
    { id: 'squinting-tongue', emoji: '😝', label: 'Squinting Tongue', lottieSource: require('../../assets/emojis/squinting-tongue.json') },
    { id: 'star-struck', emoji: '🤩', label: 'Star Struck', lottieSource: require('../../assets/emojis/star-struck.json') },
    { id: 'stuck-out-tongue', emoji: '😛', label: 'Stuck Out Tongue', lottieSource: require('../../assets/emojis/stuck-out-tongue.json') },
    { id: 'sunglasses-face', emoji: '😎', label: 'Sunglasses Face', lottieSource: require('../../assets/emojis/sunglasses-face.json') },
    { id: 'surprised', emoji: '😯', label: 'Surprised', lottieSource: require('../../assets/emojis/surprised.json') },
    { id: 'sweat', emoji: '😓', label: 'Sweat', lottieSource: require('../../assets/emojis/sweat.json') },
    { id: 'thermometer-face', emoji: '🤒', label: 'Thermometer Face', lottieSource: require('../../assets/emojis/thermometer-face.json') },
    { id: 'thinking-face', emoji: '🤔', label: 'Thinking Face', lottieSource: require('../../assets/emojis/thinking-face.json') },
    { id: 'tired', emoji: '😫', label: 'Tired', lottieSource: require('../../assets/emojis/tired.json') },
    { id: 'triumph', emoji: '😤', label: 'Triumph', lottieSource: require('../../assets/emojis/triumph.json') },
    { id: 'unamused', emoji: '😒', label: 'Unamused', lottieSource: require('../../assets/emojis/unamused.json') },
    { id: 'vomit', emoji: '🤮', label: 'Vomit', lottieSource: require('../../assets/emojis/vomit.json') },
    { id: 'warm-smile', emoji: '☺️', label: 'Warm Smile', lottieSource: require('../../assets/emojis/warm-smile.json') },
    { id: 'weary', emoji: '😩', label: 'Weary', lottieSource: require('../../assets/emojis/weary.json') },
    { id: 'wink', emoji: '😉', label: 'Wink', lottieSource: require('../../assets/emojis/wink.json') },
    { id: 'woozy', emoji: '🥴', label: 'Woozy', lottieSource: require('../../assets/emojis/woozy.json') },
    { id: 'worried', emoji: '😟', label: 'Worried', lottieSource: require('../../assets/emojis/worried.json') },
    { id: 'yawn', emoji: '🥱', label: 'Yawn', lottieSource: require('../../assets/emojis/yawn.json') },
    { id: 'yum', emoji: '😋', label: 'Yum', lottieSource: require('../../assets/emojis/yum.json') },
    { id: 'zany-face', emoji: '🤪', label: 'Zany Face', lottieSource: require('../../assets/emojis/zany-face.json') },
    { id: 'zipper-face', emoji: '🤐', label: 'Zipper Face', lottieSource: require('../../assets/emojis/zipper-face.json') },
];

export const getEmojiById = (id) => emojis.find(e => e.id === id);
export const getEmojiByLabel = (label) => emojis.find(e => e.label === label);
