const PENGUIN_MOOD_IMAGES = {
    'angry_angry': require('../../assets/penguinmoods/angry_angry.png'),
    'angry_bored': require('../../assets/penguinmoods/angry_bored.png'),
    'angry_cuddly': require('../../assets/penguinmoods/angry_cuddly.png'),
    'angry_excited': require('../../assets/penguinmoods/angry_excited.png'),
    'angry_flirtatious': require('../../assets/penguinmoods/angry_flirtatious.png'),
    'angry_relaxed': require('../../assets/penguinmoods/angry_relaxed.png'),
    'angry_sad': require('../../assets/penguinmoods/angry_sad.png'),
    'angry_sleepy': require('../../assets/penguinmoods/angry_sleepy.png'),
    'angry_stressed': require('../../assets/penguinmoods/angry_stressed.png'),
    'angry_tired': require('../../assets/penguinmoods/angry_tired.png'),
    'bored_angry': require('../../assets/penguinmoods/bored_angry.png'),
    'bored_bored': require('../../assets/penguinmoods/bored_bored.png'),
    'bored_cuddly': require('../../assets/penguinmoods/bored_cuddly.png'),
    'bored_excited': require('../../assets/penguinmoods/bored_excited.png'),
    'bored_flirtatious': require('../../assets/penguinmoods/bored_flirtatious.png'),
    'bored_relaxed': require('../../assets/penguinmoods/bored_relaxed.png'),
    'bored_sad': require('../../assets/penguinmoods/bored_sad.png'),
    'bored_sleepy': require('../../assets/penguinmoods/bored_sleepy.png'),
    'bored_stressed': require('../../assets/penguinmoods/bored_stressed.png'),
    'bored_tired': require('../../assets/penguinmoods/bored_tired.png'),
    'cuddly_angry': require('../../assets/penguinmoods/cuddly_angry.png'),
    'cuddly_bored': require('../../assets/penguinmoods/cuddly_bored.png'),
    'cuddly_cuddly': require('../../assets/penguinmoods/cuddly_cuddly.png'),
    'cuddly_excited': require('../../assets/penguinmoods/cuddly_excited.png'),
    'cuddly_flirtatious': require('../../assets/penguinmoods/cuddly_flirtatious.png'),
    'cuddly_relaxed': require('../../assets/penguinmoods/cuddly_relaxed.png'),
    'cuddly_sad': require('../../assets/penguinmoods/cuddly_sad.png'),
    'cuddly_sleepy': require('../../assets/penguinmoods/cuddly_sleepy.png'),
    'cuddly_stressed': require('../../assets/penguinmoods/cuddly_stressed.png'),
    'cuddly_tired': require('../../assets/penguinmoods/cuddly_tired.png'),
    'excited_angry': require('../../assets/penguinmoods/excited_angry.png'),
    'excited_bored': require('../../assets/penguinmoods/excited_bored.png'),
    'excited_cuddly': require('../../assets/penguinmoods/excited_cuddly.png'),
    'excited_excited': require('../../assets/penguinmoods/excited_excited.png'),
    'excited_flirtatious': require('../../assets/penguinmoods/excited_flirtatious.png'),
    'excited_relaxed': require('../../assets/penguinmoods/excited_relaxed.png'),
    'excited_sad': require('../../assets/penguinmoods/excited_sad.png'),
    'excited_sleepy': require('../../assets/penguinmoods/excited_sleepy.png'),
    'excited_stressed': require('../../assets/penguinmoods/excited_stressed.png'),
    'excited_tired': require('../../assets/penguinmoods/excited_tired.png'),
    'flirtatious_angry': require('../../assets/penguinmoods/flirtatious_angry.png'),
    'flirtatious_bored': require('../../assets/penguinmoods/flirtatious_bored.png'),
    'flirtatious_cuddly': require('../../assets/penguinmoods/flirtatious_cuddly.png'),
    'flirtatious_excited': require('../../assets/penguinmoods/flirtatious_excited.png'),
    'flirtatious_flirtatious': require('../../assets/penguinmoods/flirtatious_flirtatious.png'),
    'flirtatious_relaxed': require('../../assets/penguinmoods/flirtatious_relaxed.png'),
    'flirtatious_sad': require('../../assets/penguinmoods/flirtatious_sad.png'),
    'flirtatious_sleepy': require('../../assets/penguinmoods/flirtatious_sleepy.png'),
    'flirtatious_stressed': require('../../assets/penguinmoods/flirtatious_stressed.png'),
    'flirtatious_tired': require('../../assets/penguinmoods/flirtatious_tired.png'),
    'relaxed_angry': require('../../assets/penguinmoods/relaxed_angry.png'),
    'relaxed_bored': require('../../assets/penguinmoods/relaxed_bored.png'),
    'relaxed_cuddly': require('../../assets/penguinmoods/relaxed_cuddly.png'),
    'relaxed_excited': require('../../assets/penguinmoods/relaxed_excited.png'),
    'relaxed_flirtatious': require('../../assets/penguinmoods/relaxed_flirtatious.png'),
    'relaxed_relaxed': require('../../assets/penguinmoods/relaxed_relaxed.png'),
    'relaxed_sad': require('../../assets/penguinmoods/relaxed_sad.png'),
    'relaxed_sleepy': require('../../assets/penguinmoods/relaxed_sleepy.png'),
    'relaxed_stressed': require('../../assets/penguinmoods/relaxed_stressed.png'),
    'relaxed_tired': require('../../assets/penguinmoods/relaxed_tired.png'),
    'sad_angry': require('../../assets/penguinmoods/sad_angry.png'),
    'sad_bored': require('../../assets/penguinmoods/sad_bored.png'),
    'sad_cuddly': require('../../assets/penguinmoods/sad_cuddly.png'),
    'sad_excited': require('../../assets/penguinmoods/sad_excited.png'),
    'sad_flirtatious': require('../../assets/penguinmoods/sad_flirtatious.png'),
    'sad_relaxed': require('../../assets/penguinmoods/sad_relaxed.png'),
    'sad_sad': require('../../assets/penguinmoods/sad_sad.png'),
    'sad_sleepy': require('../../assets/penguinmoods/sad_sleepy.png'),
    'sad_stressed': require('../../assets/penguinmoods/sad_stressed.png'),
    'sad_tired': require('../../assets/penguinmoods/sad_tired.png'),
    'sleepy_angry': require('../../assets/penguinmoods/sleepy_angry.png'),
    'sleepy_bored': require('../../assets/penguinmoods/sleepy_bored.png'),
    'sleepy_cuddly': require('../../assets/penguinmoods/sleepy_cuddly.png'),
    'sleepy_excited': require('../../assets/penguinmoods/sleepy_excited.png'),
    'sleepy_flirtatious': require('../../assets/penguinmoods/sleepy_flirtatious.png'),
    'sleepy_relaxed': require('../../assets/penguinmoods/sleepy_relaxed.png'),
    'sleepy_sad': require('../../assets/penguinmoods/sleepy_sad.png'),
    'sleepy_sleepy': require('../../assets/penguinmoods/sleepy_sleepy.png'),
    'sleepy_stressed': require('../../assets/penguinmoods/sleepy_stressed.png'),
    'sleepy_tired': require('../../assets/penguinmoods/sleepy_tired.png'),
    'stressed_angry': require('../../assets/penguinmoods/stressed_angry.png'),
    'stressed_bored': require('../../assets/penguinmoods/stressed_bored.png'),
    'stressed_cuddly': require('../../assets/penguinmoods/stressed_cuddly.png'),
    'stressed_excited': require('../../assets/penguinmoods/stressed_excited.png'),
    'stressed_flirtatious': require('../../assets/penguinmoods/stressed_flirtatious.png'),
    'stressed_relaxed': require('../../assets/penguinmoods/stressed_relaxed.png'),
    'stressed_sad': require('../../assets/penguinmoods/stressed_sad.png'),
    'stressed_sleepy': require('../../assets/penguinmoods/stressed_sleepy.png'),
    'stressed_stressed': require('../../assets/penguinmoods/stressed_stressed.png'),
    'stressed_tired': require('../../assets/penguinmoods/stressed_tired.png'),
    'tired_angry': require('../../assets/penguinmoods/tired_angry.png'),
    'tired_bored': require('../../assets/penguinmoods/tired_bored.png'),
    'tired_cuddly': require('../../assets/penguinmoods/tired_cuddly.png'),
    'tired_excited': require('../../assets/penguinmoods/tired_excited.png'),
    'tired_flirtatious': require('../../assets/penguinmoods/tired_flirtatious.png'),
    'tired_relaxed': require('../../assets/penguinmoods/tired_relaxed.png'),
    'tired_sad': require('../../assets/penguinmoods/tired_sad.png'),
    'tired_sleepy': require('../../assets/penguinmoods/tired_sleepy.png'),
    'tired_stressed': require('../../assets/penguinmoods/tired_stressed.png'),
    'tired_tired': require('../../assets/penguinmoods/tired_tired.png'),
};

const VALID_MOODS = [
    'relaxed',
    'stressed',
    'excited',
    'sad',
    'sleepy',
    'angry',
    'bored',
    'tired',
    'cuddly',
    'flirtatious'
];

export const DEFAULT_PENGUIN_MOOD_IMAGE = PENGUIN_MOOD_IMAGES.relaxed_relaxed;

export const getPenguinMoodImage = (partnerMoodId, myMoodId) => {
    let partnerId = partnerMoodId || 'relaxed';
    let myId = myMoodId || 'relaxed';

    if (!VALID_MOODS.includes(partnerId)) {
        partnerId = 'relaxed';
    }
    if (!VALID_MOODS.includes(myId)) {
        myId = 'relaxed';
    }

    return PENGUIN_MOOD_IMAGES[`${partnerId}_${myId}`] || DEFAULT_PENGUIN_MOOD_IMAGE;
};

